name: CI

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpmp
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: npm install

      - name: Run CI
        run: npm run ci

      - name: Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          pnpm changeset version
          pnpm changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
